
version: "3"

services:
  laravel:
    build:
      context: .
      dockerfile: ./laravel/Dockerfile
      args:
        - TZ=${TZ}
    container_name: laravel
    volumes:
      - ./laravel:/var/www/laravel
    links:
      - mysql
    ports:
      - "8000:8000"
    environment:
      - FRONTEND_URL=next
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=mysql
      - DB_DATABASE=${DB_NAME}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASS}
      - TZ=${TZ}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}

  mail:
    container_name: mail
    image: mailhog/mailhog
      #    platform: linux/amd64
    ports:
      - "1025:1025"
      - "8045:8025"

  mysql:
    container_name: mysql
    image: mysql:8.0
#    platform: linux/x86_64
    user: mysql
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
      - TZ=${TZ}
    user: root:root
    ports:
      - ${DB_PORT}:3306

  next:
    build:
      context: .
      dockerfile: ./next/Dockerfile
      args:
        - TZ=${TZ}
    container_name: next
    tty: true
    volumes:
      - ./next:/var/www/next
    ports:
      - "3005:3000"

  pma:
    image: phpmyadmin/phpmyadmin
      # platform: linux/amd64
    container_name: pma
    depends_on:
      - mysql
    environment:
      PMA_ARBITRARY: 1
      PMA_HOSTS: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "6000:80"
