server {
        listen 80;
        listen [::]:80;
        server_name www.pik5.net;
        return 301 http://pik5.net;
}
server {
        listen 80;
        listen [::]:80;
        server_name pik5.net;
        return 301 https://$server_name$request_uri;
}
server {
        listen 443 ssl;
        listen [::]:443 ssl ipv6only=on;
        server_name pik5.net;

        ssl_certificate /etc/letsencrypt/live/pik5.net/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/pik5.net/privkey.pem;
        include /etc/letsencrypt/options-ssl-nginx.conf;
        ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        location ^~ /_next/data/ {
                limit_req  zone=perip_nextdata burst=120;
                limit_conn connperip 100;
                proxy_pass http://localhost:3005;
        }
        location ^~ /_next/static/ {
                limit_req  zone=perip_nextdata burst=200;
                proxy_pass http://localhost:3005;
        }
        location / {
                limit_req  zone=perip burst=20 nodelay;
                limit_conn connperip 50;
                proxy_pass http://localhost:3005/;
        }
}
